# -*- coding: utf-8 -*-
"""Beginners_Task_1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HwPK0Xw10bxpvuKg8JTB_06lfSaiLRUQ
"""

!pip install tensorflow_datasets

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout,BatchNormalization
from tensorflow.keras.models import Sequential
import os
import tensorflow_datasets as tfds
import tensorflow as tf

dataset, info = tfds.load('horses_or_humans', with_info=True, as_supervised=True)

class_names=info.features['label'].names
class_names

#creating a directory
for i, example in enumerate(dataset['train']):
  # example = (image, label)
  image, label = example
  save_dir = './horses_or_humans/train/{}'.format(class_names[label])
  os.makedirs(save_dir, exist_ok=True)

  filename = save_dir + "/" + "{}_{}.jpg".format(class_names[label], i)
  tf.keras.preprocessing.image.save_img(filename, image.numpy())
  # print(filename)
  # break

import cv2
horse = cv2.imread('/content/horses_or_humans/train/horses/horses_1000.jpg')
horse

humans = cv2.imread('/content/horses_or_humans/train/humans/humans_115.jpg')
humans

from google.colab.patches import cv2_imshow
cv2_imshow(horse)

from google.colab.patches import cv2_imshow
cv2_imshow(humans)

datagen = ImageDataGenerator(rescale=1./255,validation_split=0.2,rotation_range=10,
                             width_shift_range=0.1,height_shift_range=0.1,
                             shear_range=0.1,zoom_range=0.1,horizontal_flip=True)
datagen

train_generator = datagen.flow_from_directory('/content/horses_or_humans/train',target_size=(150,150),batch_size=32,
                                              class_mode='binary',subset='training')

validation_generator = datagen.flow_from_directory('/content/horses_or_humans/train',target_size = (150,150),batch_size=32,
                                                   class_mode='binary',subset='validation')

model = Sequential()
model.add(Conv2D(32,kernel_size=3,activation='relu',input_shape=(150,150,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Dropout(0.2))#1st layer

model.add(Conv2D(64,kernel_size=3,activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Dropout(0.2))#2nd layer

#3rd Layer CNN
model.add(Conv2D(128,kernel_size=3,activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Flatten())

model.add(Dense(512, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

# import shutil

# # Zip the created directory
# shutil.make_archive('horses_or_humans_dataset', 'zip', './horses_or_humans')

dataset, info = tfds.load('horses_or_humans', with_info=True, as_supervised=True)

#creating a directory
for i, example in enumerate(dataset['train']):
  # example = (image, label)
  image, label = example
  save_dir = './horses_or_humans/train/{}'.format(class_names[label])
  os.makedirs(save_dir, exist_ok=True)

  filename = save_dir + "/" + "{}_{}.jpg".format(class_names[label], i)
  tf.keras.preprocessing.image.save_img(filename, image.numpy())
  # print(filename)
  # break

model.summary()

"""**Training-Epoch✅**"""

from IPython.core import history
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=0.0001)
history = model.fit(train_generator, epochs=50, validation_data=validation_generator, callbacks=[early_stop, reduce_lr])
history.history

#save model
model.save('Horses and Humans.h5')

model_load=tf.keras.models.load_model('Horses and Humans.h5')

import requests
import numpy as np
from PIL import Image
from tensorflow.keras.preprocessing import image

# 🔹 Provide a direct image URL
img_url = "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG9yc2VzfGVufDB8fDB8fHww"
img = Image.open(requests.get(img_url, stream=True).raw).convert("RGB").resize((150, 150))

# 🔹 Convert to array
img_array = image.img_to_array(img)

# 🔹 Expand dimensions
img_array = np.expand_dims(img_array, axis=0)

# 🔹 Normalize (FIXED: normalize img_array, not img)
img_array = img_array / 255.0

# 🔹 Predict (FIXED: use img_array)
prediction = model.predict(img_array)

# 🔹 Binary classification
TH = 0.5
prediction = int(prediction[0][0] > TH)

# 🔹 Class labels
classes = {v: k for k, v in train_generator.class_indices.items()}

print(classes[prediction])

import requests
import numpy as np
from PIL import Image
from tensorflow.keras.preprocessing import image

# 🔹 Provide a direct image URL
img_url = "https://i.pinimg.com/736x/df/bd/39/dfbd397c1f13e66ccae6a669ea9c1691.jpg"
# 🔹 Load and resize image
img = Image.open(requests.get(img_url, stream=True).raw).convert("RGB").resize((150, 150))

# 🔹 Convert to array
img_array = image.img_to_array(img)

# 🔹 Expand dimensions
img_array = np.expand_dims(img_array, axis=0)

# 🔹 Normalize (FIXED: normalize img_array, not img)
img_array = img_array / 255.0

# 🔹 Predict (FIXED: use img_array)
prediction = model.predict(img_array)

# 🔹 Binary classification
TH = 0.5
prediction = int(prediction[0][0] > TH)

# 🔹 Class labels
classes = {v: k for k, v in train_generator.class_indices.items()}

print(classes[prediction])